app:
  build: .
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - .:/usr/src/app
db:
  image: mdillon/postgis
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=bicimapa
    - POSTGRES_PASSWORD=bicimapa
    - POSTGRES_DB=bicimapa
  volumes:
    - ./docker/pgdata:/var/lib/postgresql/data
