# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgis
  timeout: 5000
  encoding: unicode
  host: db
  pool: 5
  database: bicimapa
  username: bicimapa
  password: bicimapa

production:
  adapter: postgis
  timeout: 5000
  encoding: unicode
  host: localhost
  pool: 5
  database: bicimapa
  username: bicimapa
  password: bicimapa
